name: cityfix
description: CityFix — منصة الإبلاغ عن مشاكل المدينة — ولاية الأغواط
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # HTTP
  http: ^1.2.0
  
  # Storage
  shared_preferences: ^2.2.2
  
  # Camera & Image
  image_picker: ^1.0.7
  
  # Location / GPS
  geolocator: ^11.0.0
  permission_handler: ^11.3.0
  
  # Firebase
  firebase_core: ^2.27.0
  firebase_messaging: ^14.7.20
  flutter_local_notifications: ^17.2.1
  
  # UI
  cached_network_image: ^3.3.1
  flutter_svg: ^2.0.9
  shimmer: ^3.0.0
  
  # Utils
  uuid: ^4.3.3
  intl: ^0.19.0
  url_launcher: ^6.2.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
